---
- name: "Pre-deploy checks"
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: "Create group subfolder structure"
  hosts:
    - user_interface
    - chaperone
  roles:
    - create_group_subfolder_structure
...
