---
- name: "Pre-deploy checks"
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: "Manage cronjobs"
  hosts:
    - user_interface
    - data_staging
    - chaperone
  roles:
    - manage_cronjobs
...
