---
- name: "Pre-deploy checks"
  ansible.builtin.import_playbook: pre_deploy_checks.yml

- name: "Manage notifications"
  hosts:
    - user_interface
    - chaperone
  roles:
    - manage_notifications
...
