---
- import_playbook: single_role_playbooks/pre_deploy_checks.yml
- import_playbook: single_role_playbooks/install-easybuild.yml
- import_playbook: single_role_playbooks/fetch-extra-easyconfigs.yml
- import_playbook: single_role_playbooks/fetch-sources-and-refdata.yml
- import_playbook: single_role_playbooks/install-modules-with-easybuild.yml
- import_playbook: single_role_playbooks/create-group-subfolder-structure.yml
...
