---
- name: Sanity checks before we start.
  hosts: all
  #remote_user: DO NOT specify a user here. Specify login name in your ~/.ssh/config instead.
  pre_tasks:
    - name: Verify Ansible version meets requirements.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: 'You must update Ansible to at least 2.7.x to use this playbook.'

- hosts: DAI, helper
  roles:
    - install-easybuild
    - fetch-extra-easyconfigs
    - fetch-sources-and-refdata
    - install-modules-with-easybuild

- hosts: UI
  roles:
    - create-group-subfolder-structure
...
