---
- hosts: passage+leucine-zipper+chaperone
  #remote_user: DO NOT specify a user here. Specify login name in your ~/.ssh/config instead.
  pre_tasks:
    - name: Verify Ansible version meets requirements.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: 'You must update Ansible to at least 2.7.x to use this playbook.'
  roles:
  - role: easybuild-install
  tasks:
  - name: Create main folder structure for software and reference data.
    file: dest="{{item}}" state='directory' mode="{{ MODE_2775_HARD }}"
    with_items:
      - "{{ easybuild_software_dir }}/easyconfigs"
      - "{{ easybuild_sources_dir }}/e/easyconfigs"
      - "{{ pb_ebconfigs_prefix }}"
      - "{{ HPC_ENV_PREFIX }}/data"
  - name: Get EasyConfigs.
    get_url: url="{{ item.url }}" dest="{{ item.dest }}" checksum="{{ item.checksum }}" mode="{{ MODE_0664_HARD }}"
    with_items:
      - url: "https://github.com/molgenis/easybuild-easyconfigs/archive/{{ pb_ebconfigs_version }}.tar.gz"
        dest: "{{ easybuild_sources_dir }}/e/easyconfigs/"
        checksum: "{{ pb_ebconfigs_checksum }}"
  - name: Extract EasyConfigs.
    unarchive: src="{{ item.src }}" dest="{{ item.dest }}" remote_src=yes mode="{{ MODE__775_SOFT }}"
    with_items:
      - src:  "{{ easybuild_sources_dir }}/e/easyconfigs/easybuild-easyconfigs-{{ pb_ebconfigs_version }}.tar.gz"
        dest: "{{ easybuild_software_dir }}/easyconfigs"
  - name: Deploy NGS_Automated module with EasyBuild.
    shell: |
           source {{ easybuild_modules_dir }}/modules.bashrc
           module load "EasyBuild/{{ easybuild_eb_version }}"
           eb --robot --robot-paths="{{ pb_ebconfigs_prefix }}/:" \
              {{ pb_ebconfigs_prefix }}/n/NGS_Automated/NGS_Automated-{{ pb_ngs_automated_version }}.eb
    environment:
      SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
...
