---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#

#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here,
#       please make sure to add corresponding values in group_vars/all.yml
#
lua_version: '5.1.4.9'
lmod_version: '7.8.8'
easybuild_version: '3.7.1'
extra_easyconfigs_version: '2.8.31'
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure: [
  { group: 'umcg-atd',
    lfs: 'scr01',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-atd-ateambot',
    subfolders: ['generatedscripts', 'logs', 'projects', 'rawdata', 'runs', 'Samplesheets', 'tmp'] },
  { group: 'umcg-gd',
    lfs: 'scr01',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-gd-ateambot',
    subfolders: ['generatedscripts', 'logs', 'projects', 'rawdata', 'runs', 'Samplesheets', 'tmp'] },
]
#
# Sources, software and reference data to install/fetch.
#
public_sources: [
  'g/GCC/gmp-6.0.0a.tar.bz2',
  'g/GCC/mpc-1.0.2.tar.gz',
  'g/GCC/gcc-4.9.3.tar.bz2',
  'g/GCC/mpfr-3.1.2.tar.gz',
  'h/hwloc/hwloc-1.11.0.tar.gz',
  'n/numactl/numactl-2.0.10.tar.gz',
  'o/OpenMPI/openmpi-1.8.8.tar.gz',
  'z/zlib/zlib-1.2.8.tar.gz',
]
private_sources: [
  'j/Java/jdk-8u45-linux-x64.tar.gz',
]
refdata: [
  'Prepkits',
]
easyconfigs: [
  'c/cluster-utils/cluster-utils-v18.08.1.eb',
  'd/depad-utils/depad-utils-v19.02.1.eb',
  'n/NGS_Automated/NGS_Automated-2.0.18-NGS_Demultiplexing-2.3.0.eb',
]
...