---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#

#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here,
#       please make sure to add corresponding values in group_vars/all.yml
#
lua_version: '5.1.4.9'
lmod_version: '7.8.8'
easybuild_version: '3.7.1'
extra_easyconfigs_version: '2.8.31'
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure: [
  { group: 'umcg-atd',
    lfs: 'tmp08',
    mode: "{{ MODE_2770_HARD }}",
    owner: '',
    subfolders: ['generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp'] },
  { group: 'umcg-atd',
    lfs: 'prm08',
    mode: "{{ MODE_2750_HARD }}",
    owner: 'umcg-atd-dm',
    subfolders: ['generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets'] },
]
#
# Sources, software and reference data to install/fetch.
#
public_sources: [
  'f/flex/flex-2.5.39.tar.gz',
  'g/GCC/gmp-6.0.0a.tar.bz2',
  'g/GCC/mpc-1.0.2.tar.gz',
  'g/GCC/gcc-4.9.3.tar.bz2',
  'g/GCC/mpfr-3.1.2.tar.gz',
  'h/hwloc/hwloc-1.11.0.tar.gz',
#  'n/NASM/nasm-2.11.08.tar.bz2',
  'n/numactl/numactl-2.0.10.tar.gz',
  'o/OpenMPI/openmpi-1.8.8.tar.gz',
  'z/zlib/zlib-1.2.8.tar.gz',
#  's/snpEff/snpEff_v4_3_core.zip',
#  'i/io_lib/io_lib-1.14.6.tar.gz',
#  'e/expat/expat-2.1.0.tar.gz',
#  'l/libpng/libpng-1.6.21.tar.gz',
]
private_sources: [
  'g/GATK/GenomeAnalysisTK-3.7.tar.bz2',
  'j/Java/jdk-11.0.2-linux-x64_bin.tar.gz',
]
refdata: [
  'CGD',
  'ClinVar',
]
easyconfigs: [
  'c/cluster-utils/cluster-utils-v18.08.1-foss-2018b.eb',
  'd/depad-utils/depad-utils-v19.06.1.eb',
]
...