---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#

#
# Versions of components of our HPC environment, which is managed using Lua+Lmod+EasyBuild.
# NOTE: when introducing a new version number here,
#       please make sure to add corresponding values in group_vars/all.yml
#
lua_version: '5.1.4.9'
lmod_version: '7.8.8'
easybuild_version: '4.3.2'
extra_easyconfigs_version: '2.8.44'
#
# Group folder structures to construct on shared storage systems.
#
group_subfolder_structure: [
  { group: 'umcg-atd',
    lfs: 'tmp06',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-atd-ateambot',
    subfolders: ['concordance', 'generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp', ' trendanalysis'] },
  { group: 'umcg-gap',
    lfs: 'tmp06',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-gap-ateambot',
    subfolders: ['DiagnosticOutput', 'generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp'] },
  { group: 'umcg-gd',
    lfs: 'tmp06',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-gd-ateambot',
    subfolders: ['concordance', 'generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp', ' trendanalysis'] },
  { group: 'umcg-genomescan',
    lfs: 'tmp06',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-genomescan-ateambot',
    subfolders: ['logs', 'rawdata', 'runs', 'Samplesheets'] },
  { group: 'umcg-gsad',
    lfs: 'tmp06',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-gsad-ateambot',
    subfolders: ['concordance', 'DiagnosticOutput', 'generatedscripts', 'logs', 'projects', 'rawdata', 'Samplesheets', 'tmp'] },
  { group: 'umcg-gst',
    lfs: 'tmp06',
    mode: "{{ MODE_2770_HARD }}",
    owner: 'umcg-gst-ateambot',
    subfolders: ['logs', 'rawdata', 'runs', 'Samplesheets'] },
]
#
# Sources, software and reference data to install/fetch.
#
public_sources: [
  'f/flex/flex-2.5.39.tar.gz',
  'g/GCC/gmp-6.0.0a.tar.bz2',
  'g/GCC/mpc-1.0.2.tar.gz',
  'g/GCC/gcc-4.9.3.tar.bz2',
  'g/GCC/mpfr-3.1.2.tar.gz',
  'h/hwloc/hwloc-1.11.0.tar.gz',
  'n/NASM/nasm-2.11.08.tar.bz2',
  'n/numactl/numactl-2.0.10.tar.gz',
  'o/OpenMPI/openmpi-1.8.8.tar.gz',
  'z/zlib/zlib-1.2.8.tar.gz',
  's/snpEff/snpEff_v4_3_core.zip',
  'i/io_lib/io_lib-1.14.6.tar.gz',
  'e/expat/expat-2.1.0.tar.gz',
  'l/libpng/libpng-1.6.21.tar.gz',
]
private_sources: [
  'g/GATK/GenomeAnalysisTK-3.7.tar.bz2',
  'j/Java/jdk-7u80-linux-x64.tar.gz',
  'j/Java/jdk-8u45-linux-x64.tar.gz',
  'j/Java/jdk-8u74-linux-x64.tar.gz',
  'j/Java/jdk-11.0.2-linux-x64_bin.tar.gz',
]
refdata: [
  'dbSNP',
  '1000G',
  'Agilent',
  'CADD',
  'CGD',
  'ClinVar',
  'Controls_Convading_XHMM',
  'GSAarray',
  'Ensembl',
  'ExAC',
  'ManVarList',
#  'gnomAD',
  'GAVIN',
  'GeneNetwork',
  'HPO',
  'UMCG',
  'XHMM',
  'gonl',
  'inSilico',
  'snpEff-4.3',
]
easyconfigs: [
  'c/cluster-utils/cluster-utils-v18.08.1.eb',
  'd/depad-utils/depad-utils-v19.02.1.eb',
  'c/ConcordanceCheck/ConcordanceCheck-2.1.0.eb',
  'n/NGS_Automated/NGS_Automated-3.6.2-bare.eb',
  'n/NGS_Automated/NGS_Automated-3.6.2-GAP-2.3.1.eb',
  'n/NGS_Automated/NGS_Automated-3.6.2-NGS_DNA-3.6.0.eb',
]
...