---
#
# EasyBuild.
#
- name: Download EasyBuild bootstrap script and deps for offline bootstrapping.
  get_url: url="{{ item.url }}" dest="{{ item.dest }}" checksum="{{ item.checksum }}" mode="{{ MODE_0664_HARD }}"
  with_items:
    - url: "https://raw.githubusercontent.com/easybuilders/easybuild-framework/{{ easybuild_bs_hash }}/easybuild/scripts/bootstrap_eb.py"
      dest: "{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/bootstrap_eb_{{ easybuild_bs_version }}.py"
      checksum: "{{ easybuild_bs_checksum }}"
    - url: "{{ easybuild_vsc_install_url }}"
      dest: "{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/"
      checksum: "{{ easybuild_vsc_install_checksum }}"
    - url: "{{ easybuild_vsc_base_url }}"
      dest: "{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/"
      checksum: "{{ easybuild_vsc_base_checksum }}"
    - url: "{{ easybuild_framework_url }}"
      dest: "{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/"
      checksum: "{{ easybuild_framework_checksum }}"
    - url: "{{ easybuild_easyblocks_url }}"
      dest: "{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/"
      checksum: "{{ easybuild_easyblocks_checksum }}"
    - url: "{{ easybuild_easyconfigs_url }}"
      dest: "{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/"
      checksum: "{{ easybuild_easyconfigs_checksum }}"
- name: Install latest EasyBuild version with bootstrap script.
  #
  # Ansible doesn't run task in a login shell, so we have to source the EasyBuild config manually.
  #
  shell: |
         source ~/.modulesrc
         umask 0002
         export EASYBUILD_BOOTSTRAP_SOURCEPATH="{{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/"
         python {{ easybuild_sources_dir }}/e/EasyBuild/{{ easybuild_eb_version }}/bootstrap_eb_{{ easybuild_bs_version }}.py {{ HPC_ENV_PREFIX }}
- name: Check if the required EasyBuild version is installed.
  shell: |
         source ~/.modulesrc >/dev/null 2>&1
         module load EasyBuild/{{ easybuild_eb_version }}
         eb --version 2>&1 | head -1 | sed 's|^This is EasyBuild \([0-9\.]*\).*$|\1|'
  args:
    executable: /bin/bash
    warn: no
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  changed_when: false
  failed_when: false
  check_mode: no
  register: eb_installed_version
- name: Determine if the required EasyBuild version needs to be installed.
  set_fact:
    eb_install_from_source: true
  when: 'eb_installed_version|failed or (eb_installed_version.stdout | version_compare(easybuild_eb_version, operator="!="))'
- name: Report EasyBuild status.
  debug:
    msg: 'Will install the required EasyBuild version with the latest EasyBuild version as the bootstrapped version is not the requested version. (Detected {{ eb_installed_version.stdout }} and need {{ easybuild_eb_version }}.)'
  when: eb_install_from_source|default(false)
- name: Install required EasyBuild version with EasyBuild.
  shell: |
         source ~/.modulesrc
         umask 0002
         module load EasyBuild
         eb --software="EasyBuild,{{ easybuild_eb_version }}"
  environment:
    SOURCE_HPC_ENV: "True"   # Required to source our modules.bashrc in non-interactive shells.
  when: eb_install_from_source|default(false)
...
