---
#
# Site specific values to override defaults for variables.
#
# Conventions for global environment variables:
# Use UPPERCASE underscore separated names like for shell env vars.
#
GROUP: "umcg-gd"
#
# Conventions for playbook variables:
# Use lowercase underscore separated names.
#
pb_ngs_dna_version: 'NGS_Automated-2.0.18-NGS_DNA-3.5.4'
pb_ngs_automated_version: '2.0.18-bare'
extra_easyconfigs_version: '2.8.30'
extra_easyconfigs_checksum: 'sha256:5cde691a569d46d8d38624565fdd8d9bbcecb50f4725f6a0561db3187a12dd11'
pb_tmp_lfs: "tmp05"
...