---
#
# Lmod.
#
- name: Download Lmod.
  ansible.builtin.get_url:
    url: "{{ lmod_releases[lmod_version]['url'] }}"
    dest: "{{ easybuild_sources_dir }}/l/Lmod/{{ lmod_version }}.tar.gz"
    checksum: "{{ lmod_releases[lmod_version]['checksum'] }}"
    mode: "{{ MODE_0664_HARD }}"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Decompress Lmod.
  ansible.builtin.unarchive:
    src: "{{ easybuild_sources_dir }}/l/Lmod/{{ lmod_version }}.tar.gz"
    dest: "{{ easybuild_sources_dir }}/l/Lmod/"
    copy: false
    mode: "{{ MODE__775_SOFT }}"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Compile and install Lmod.
  ansible.builtin.shell:
    cmd: |
         export PATH={{ easybuild_software_dir }}/Lua/{{ lua_version }}/bin:$PATH
         cd {{ easybuild_sources_dir }}/l/Lmod/Lmod-{{ lmod_version }}
         umask 0002
         ./configure --prefix={{ easybuild_software_dir }} \
                     --with-lua-include={{ easybuild_software_dir }}/Lua/{{ lua_version }}/include \
                     --with-mpathSearch=YES \
                     --with-caseIndependentSorting=YES \
             && make install
  changed_when: true
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"
...
