---
#
# Lua.
#
- name: Create required directories.
  ansible.builtin.file:
    path: "{{ item }}"
    state: 'directory'
    mode: "{{ MODE_2775_HARD }}"
  with_items:
    - "{{ easybuild_sources_dir }}/l/Lua"
    - "{{ easybuild_software_dir }}/Lua/{{ lua_version }}"
    - "{{ easybuild_software_dir }}/EasyBuild/"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Download Lua.
  ansible.builtin.get_url:
    url: "{{ lua_releases[lua_version]['url'] }}"
    dest: "{{ easybuild_sources_dir }}/l/Lua/lua-{{ lua_version }}.tar.bz2"
    mode: "{{ MODE_0664_HARD }}"
    checksum: "{{ lua_releases[lua_version]['checksum'] }}"
    timeout: 60
    validate_certs: false  # Sourceforge redirects to https and this fails when Python on the target host is version <= 2.6.6.
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Decompress downloaded Lua source code archive.
  ansible.builtin.unarchive:
    src: "{{ easybuild_sources_dir }}/l/Lua/lua-{{ lua_version }}.tar.bz2"
    dest: "{{ easybuild_sources_dir }}/l/Lua/"
    copy: false
    mode: "{{ MODE__775_SOFT }}"
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"

- name: Compile and install Lua.
  ansible.builtin.shell:
    cmd: |
         cd {{ easybuild_sources_dir }}/l/Lua/lua-{{ lua_version }}
         umask 0002
         ./configure --with-static=yes \
                     --prefix={{ easybuild_software_dir }}/Lua/{{ lua_version }} \
             && make install
  changed_when: true
  become: "{% if eb_user is defined and eb_user | length > 0 %}true{% else %}false{% endif %}"
  become_user: "{{ eb_user | default(omit) }}"
...
