---
#
# Lua.
#
- name: Install Lua old style.
  ansible.builtin.include_tasks: tasks/install_lua_old.yml
  when: lua_version is version('5.1.4.9', '==')

- name: Install Lua new style.
  ansible.builtin.include_tasks: tasks/install_lua_new.yml
  when: lua_version is version('5.1.4.9', '>')
...
